name: wemapgl_example
description: Demonstrates how to use the wemapgl plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  location: ^2.5.4
  weather_icons: ^2.0.1
  connectivity: ^0.4.8+1
  fluttertoast: ^3.1.0
  transformer_page_view:
  flutter_svg: ^0.21.0
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  wemapgl:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/setting.jpeg
    - assets/bg/thaibinh.jpg
    - assets/bg/hanoi.jpg
    - assets/bg/london.jpg
    - assets/bg/sydney.jpg
    - assets/bg/hochiminhcity.jpg
    - assets/bgimg/default/brokenclouds.jpeg
    - assets/bgimg/default/Clearnight.jpeg
    - assets/bgimg/default/clearsky.jpeg
    - assets/bgimg/default/Clearsunrise.jpeg
    - assets/bgimg/default/Cloudsnight.jpeg
    - assets/bgimg/default/Cloudssunrise.jpeg
    - assets/bgimg/default/fewclouds.jpeg
    - assets/bgimg/default/heavyintensityrain.jpeg
    - assets/bgimg/default/lightrain.jpeg
    - assets/bgimg/default/moderaterain.jpeg
    - assets/bgimg/default/overcastclouds.jpeg
    - assets/bgimg/default/Rainnight.jpeg
    - assets/bgimg/default/Rainsunrise.jpeg
    - assets/bgimg/default/scatteredclouds.jpeg
    - assets/bgimg/chinese/brokenclouds.jpeg
    - assets/bgimg/chinese/Clearnight.jpeg
    - assets/bgimg/chinese/clearsky.jpeg
    - assets/bgimg/chinese/Clearsunrise.jpeg
    - assets/bgimg/chinese/Cloudsnight.jpeg
    - assets/bgimg/chinese/Cloudssunrise.jpeg
    - assets/bgimg/chinese/fewclouds.jpeg
    - assets/bgimg/chinese/heavyintensityrain.jpeg
    - assets/bgimg/chinese/lightrain.jpeg
    - assets/bgimg/chinese/moderaterain.jpeg
    - assets/bgimg/chinese/overcastclouds.jpeg
    - assets/bgimg/chinese/Rainnight.jpeg
    - assets/bgimg/chinese/Rainsunrise.jpeg
    - assets/bgimg/chinese/scatteredclouds.jpeg
    - assets/bgimg/canvas/brokenclouds.jpeg
    - assets/bgimg/canvas/Clearnight.jpeg
    - assets/bgimg/canvas/clearsky.jpeg
    - assets/bgimg/canvas/Clearsunrise.jpeg
    - assets/bgimg/canvas/Cloudsnight.jpeg
    - assets/bgimg/canvas/Cloudssunrise.jpeg
    - assets/bgimg/canvas/fewclouds.jpeg
    - assets/bgimg/canvas/heavyintensityrain.jpeg
    - assets/bgimg/canvas/lightrain.jpeg
    - assets/bgimg/canvas/moderaterain.jpeg
    - assets/bgimg/canvas/overcastclouds.jpeg
    - assets/bgimg/canvas/Rainnight.jpeg
    - assets/bgimg/canvas/Rainsunrise.jpeg
    - assets/bgimg/canvas/scatteredclouds.jpeg
    - assets/bgimg/photo/brokenclouds.jpeg
    - assets/bgimg/photo/Clearnight.jpeg
    - assets/bgimg/photo/clearsky.jpeg
    - assets/bgimg/photo/Clearsunrise.jpeg
    - assets/bgimg/photo/Cloudsnight.jpeg
    - assets/bgimg/photo/Cloudssunrise.jpeg
    - assets/bgimg/photo/fewclouds.jpeg
    - assets/bgimg/photo/heavyintensityrain.jpeg
    - assets/bgimg/photo/lightrain.jpeg
    - assets/bgimg/photo/moderaterain.jpeg
    - assets/bgimg/photo/overcastclouds.jpeg
    - assets/bgimg/photo/Rainnight.jpeg
    - assets/bgimg/photo/Rainsunrise.jpeg
    - assets/bgimg/photo/scatteredclouds.jpeg
    - assets/bgimg/pixel/brokenclouds.jpeg
    - assets/bgimg/pixel/Clearnight.jpeg
    - assets/bgimg/pixel/clearsky.jpeg
    - assets/bgimg/pixel/Clearsunrise.jpeg
    - assets/bgimg/pixel/Cloudsnight.jpeg
    - assets/bgimg/pixel/Cloudssunrise.jpeg
    - assets/bgimg/pixel/fewclouds.jpeg
    - assets/bgimg/pixel/heavyintensityrain.jpeg
    - assets/bgimg/pixel/lightrain.jpeg
    - assets/bgimg/pixel/moderaterain.jpeg
    - assets/bgimg/pixel/overcastclouds.jpeg
    - assets/bgimg/pixel/Rainnight.jpeg
    - assets/bgimg/pixel/Rainsunrise.jpeg
    - assets/bgimg/pixel/scatteredclouds.jpeg
    - assets/icon/brokenclouds.svg
    - assets/icon/Clearnight.svg
    - assets/icon/clearsky.svg
    - assets/icon/Cloudsnight.svg
    - assets/icon/fewclouds.svg
    - assets/icon/heavyintensityrain.svg
    - assets/icon/lightrain.svg
    - assets/icon/moderaterain.svg
    - assets/icon/overcastclouds.svg
    - assets/icon/Rainnight.svg
    - assets/icon/scatteredclouds.svg
    - assets/icon/sunrise.svg
    - assets/theme/chinese.jpeg
    - assets/theme/canvas.jpeg
    - assets/theme/default.jpeg
    - assets/theme/photo.jpeg
    - assets/theme/pixel.jpeg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
